on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ./fonts/lato/*.ttf
            ./fonts/raleway/*.otf
      - name: Prepublish
        run: mv resume.pdf dist/index.html
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: maxpeterson-resume
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
